### ISSUE TITLE
error: the trait bound `url::Url: serde::Deserialize` is not satisfied

### ISSUE THREAD

**Issue by ollivera** [indiv0/xkcd-rs#3]
I can't build it. I am using rustc 1.11.0 (9b21dcd6a 2016-08-15)

 error: the trait bound `url::Url: serde::Deserialize` is not satisfied [E0277]

**Comment by indiv0** [comment]
Sorry, somehow I missed your issue. My apologies.

That error indicates to me that somehow, the feature `serde` isn't getting enabled for the `url` crate (it should be done by my crate [here](https://github.com/indiv0/xkcd-rs/blob/master/Cargo.toml#L51)). Any ideas why this might be happening?

**Comment by indiv0** [comment]
Closing this issue due to lack of response.

Will re-open if requested.
